// <auto-generated />
using System;
using DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Entities.ActiveOrder", b =>
                {
                    b.Property<int>("ActiveOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChecknInDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime2");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("HotelRoomId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActiveOrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("HotelRoomId");

                    b.ToTable("ActiveOrders");
                });

            modelBuilder.Entity("DAL.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DAL.Entities.HotelRoom", b =>
                {
                    b.Property<int>("HotelRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeComfortId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSizeId")
                        .HasColumnType("int");

                    b.HasKey("HotelRoomId");

                    b.HasIndex("TypeComfortId");

                    b.HasIndex("TypeSizeId");

                    b.ToTable("HotelRooms");

                    b.HasData(
                        new
                        {
                            HotelRoomId = 1,
                            Number = "10",
                            Price = 100m,
                            TypeComfortId = 1,
                            TypeSizeId = 1
                        },
                        new
                        {
                            HotelRoomId = 2,
                            Number = "11",
                            Price = 100m,
                            TypeComfortId = 1,
                            TypeSizeId = 1
                        },
                        new
                        {
                            HotelRoomId = 3,
                            Number = "12",
                            Price = 200m,
                            TypeComfortId = 2,
                            TypeSizeId = 1
                        },
                        new
                        {
                            HotelRoomId = 4,
                            Number = "13",
                            Price = 200m,
                            TypeComfortId = 2,
                            TypeSizeId = 2
                        },
                        new
                        {
                            HotelRoomId = 5,
                            Number = "20",
                            Price = 250m,
                            TypeComfortId = 2,
                            TypeSizeId = 3
                        },
                        new
                        {
                            HotelRoomId = 6,
                            Number = "21",
                            Price = 250m,
                            TypeComfortId = 2,
                            TypeSizeId = 5
                        },
                        new
                        {
                            HotelRoomId = 7,
                            Number = "22",
                            Price = 300m,
                            TypeComfortId = 3,
                            TypeSizeId = 1
                        },
                        new
                        {
                            HotelRoomId = 8,
                            Number = "30",
                            Price = 400m,
                            TypeComfortId = 3,
                            TypeSizeId = 2
                        },
                        new
                        {
                            HotelRoomId = 9,
                            Number = "31",
                            Price = 400m,
                            TypeComfortId = 4,
                            TypeSizeId = 3
                        },
                        new
                        {
                            HotelRoomId = 10,
                            Number = "40",
                            Price = 600m,
                            TypeComfortId = 5,
                            TypeSizeId = 6
                        },
                        new
                        {
                            HotelRoomId = 11,
                            Number = "50",
                            Price = 800m,
                            TypeComfortId = 6,
                            TypeSizeId = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.TypeComfort", b =>
                {
                    b.Property<int>("TypeComfortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comfort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeComfortId");

                    b.ToTable("TypeComfort");

                    b.HasData(
                        new
                        {
                            TypeComfortId = 1,
                            Comfort = "Standart"
                        },
                        new
                        {
                            TypeComfortId = 2,
                            Comfort = "Suite"
                        },
                        new
                        {
                            TypeComfortId = 3,
                            Comfort = "De_Luxe"
                        },
                        new
                        {
                            TypeComfortId = 4,
                            Comfort = "Duplex"
                        },
                        new
                        {
                            TypeComfortId = 5,
                            Comfort = "Family_Room"
                        },
                        new
                        {
                            TypeComfortId = 6,
                            Comfort = "Honeymoon_Room"
                        });
                });

            modelBuilder.Entity("DAL.Entities.TypeSize", b =>
                {
                    b.Property<int>("TypeSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeSizeId");

                    b.ToTable("TypeSize");

                    b.HasData(
                        new
                        {
                            TypeSizeId = 1,
                            Size = "SGL"
                        },
                        new
                        {
                            TypeSizeId = 2,
                            Size = "DBL"
                        },
                        new
                        {
                            TypeSizeId = 3,
                            Size = "DBL_TWN"
                        },
                        new
                        {
                            TypeSizeId = 4,
                            Size = "TRPL"
                        },
                        new
                        {
                            TypeSizeId = 5,
                            Size = "DBL_EXB"
                        },
                        new
                        {
                            TypeSizeId = 6,
                            Size = "TRPL_EXB"
                        });
                });

            modelBuilder.Entity("DAL.Entities.ActiveOrder", b =>
                {
                    b.HasOne("DAL.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.HotelRoom", "HotelRoom")
                        .WithMany()
                        .HasForeignKey("HotelRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Entities.HotelRoom", b =>
                {
                    b.HasOne("DAL.Entities.TypeComfort", "TypeComfort")
                        .WithMany()
                        .HasForeignKey("TypeComfortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.TypeSize", "TypeSize")
                        .WithMany()
                        .HasForeignKey("TypeSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
